# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'odrive.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_odriveMainWindow(object):
    def setupUi(self, odriveMainWindow):
        odriveMainWindow.setObjectName("odriveMainWindow")
        odriveMainWindow.resize(863, 643)
        grid = QtWidgets.QGridLayout()
        odriveMainWindow.setLayout(grid)

        self.treeView = QtWidgets.QTreeView()
        self.treeView.setObjectName("treeView")
        grid.addWidget(self.treeView, 0, 0, 1, 1)

        # self.centralwidget = QtWidgets.QWidget(odriveMainWindow)
        # self.centralwidget.setObjectName("centralwidget")
        # self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        # self.horizontalLayoutWidget.setGeometry(QtCore.QRect(160, 110, 160, 80))
        # self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        # self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        # self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        # self.horizontalLayout.setObjectName("horizontalLayout")
        # self.widget = QtWidgets.QWidget(self.horizontalLayoutWidget)
        # self.widget.setObjectName("widget")
        # self.horizontalLayout.addWidget(self.widget)
        # odriveMainWindow.setCentralWidget(self.centralwidget)
        # self.menubar = QtWidgets.QMenuBar(odriveMainWindow)
        # self.menubar.setGeometry(QtCore.QRect(0, 0, 863, 22))
        # self.menubar.setObjectName("menubar")
        # odriveMainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(odriveMainWindow)
        self.statusbar.setObjectName("statusbar")
        odriveMainWindow.setStatusBar(self.statusbar)

        # self.retranslateUi(odriveMainWindow)
        QtCore.QMetaObject.connectSlotsByName(odriveMainWindow)

    def retranslateUi(self, odriveMainWindow):
        _translate = QtCore.QCoreApplication.translate
        odriveMainWindow.setWindowTitle(_translate("odriveMainWindow", "MainWindow"))
